export const HAMSTER_EVENTS = Object.freeze({
  PAGE_VIEWED: "page.viewed",
  MANUAL_REVEAL: "hamster.revealed",
  TIMER_COMPLETED: "timer.completed",
  MEMORY_CORRECT: "memory.correct",
  WEATHER_CHECKED: "weather.checked",
});

export const hamsterEventPolicies = Object.freeze({
  [HAMSTER_EVENTS.MANUAL_REVEAL]: {
    displayCooldownMs: 20 * 60 * 60 * 1000,
    relationshipCooldownMs: 20 * 60 * 60 * 1000,
  },
  [HAMSTER_EVENTS.MEMORY_CORRECT]: {
    displayCooldownMs: 20 * 60 * 60 * 1000,
    relationshipCooldownMs: 20 * 60 * 60 * 1000,
  },
  [HAMSTER_EVENTS.TIMER_COMPLETED]: {
    bypassCooldownWithActiveQuest: true,
    displayCooldownMs: 30 * 60 * 1000,
    relationshipCooldownMs: 30 * 60 * 1000,
  },
  [HAMSTER_EVENTS.WEATHER_CHECKED]: {
    bypassCooldownWithActiveQuest: true,
    displayCooldownMs: 30 * 60 * 1000,
    relationshipCooldownMs: 20 * 60 * 60 * 1000,
  },
});

export const hamsterKeepsakes = Object.freeze({
  "brass-button": {
    name: "A brass button",
    description: "Warm still. Its thread was cut cleanly.",
  },
  "rain-darkened-cloak": {
    name: "A rain-darkened cloak",
    description: "Heavy at the hem. It remembers weather that has passed.",
  },
  "sun-warmed-cloak": {
    name: "A sun-warmed cloak",
    description: "Needlessly packed. Pleasantly warm all the same.",
  },
  "black-seed": {
    name: "A black seed",
    description: "Found where the floor leaned with the turning world.",
  },
});

// Dialogue is data on purpose: adding or removing a line should not require
// changing relationship, persistence, or rendering code.
const wanderingThoughts = [
  ["pockets", "A quest is mostly deciding which pocket the provisions are in."],
  ["burden", "A heavy burden, this seed. I could eat it. That would settle things."],
  ["cloak", "The cloak is for travelling. I am travelling to the cupboard."],
  ["door", "I painted the door green. It has improved my opinion of staying home."],
  ["map", "There is a dragon on this map. I have folded that part underneath."],
  ["riddle", "I know a riddle. The answer is food. You may begin."],
  ["mountain", "From down here, most things are a mountain."],
  ["bravery", "I was very brave earlier. Nobody was looking, which helped."],
  ["footsteps", "I heard footsteps on the road. Put the kettle on, just in case."],
  ["ending", "A good story ends somewhere warm, with crumbs."],
].map(([id, text], index) => ({
  id: `ambient-road-${id}`,
  minAgeMs: Math.floor(index / 3) * 24 * 60 * 60 * 1000,
  minDistinctPages: index >= 5 ? 3 : 0,
  text,
  event: HAMSTER_EVENTS.MANUAL_REVEAL,
  stage: 0,
  minRelationshipCount: 1,
}));

const rememberedMoments = [
  {
    id: "remembered-first-timer",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 0,
    priority: 2,
    requiresEvent: HAMSTER_EVENTS.TIMER_COMPLETED,
    minRequiredEventCount: 1,
    minTimeSinceRequiredEventMs: 20 * 60 * 60 * 1000,
    text: "Still keeping that final second safe.",
  },
  {
    id: "remembered-five-timers",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 0,
    priority: 3,
    requiresEvent: HAMSTER_EVENTS.TIMER_COMPLETED,
    minRequiredEventCount: 5,
    minTimeSinceRequiredEventMs: 20 * 60 * 60 * 1000,
    text: "Five small ages ended together. I kept one crumb from each.",
  },
  {
    id: "remembered-memory-round",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 0,
    priority: 2,
    requiresEvent: HAMSTER_EVENTS.MEMORY_CORRECT,
    minRequiredEventCount: 1,
    minTimeSinceRequiredEventMs: 20 * 60 * 60 * 1000,
    text: "I remember the number you carried. Well. The important parts.",
  },
  {
    id: "remembered-ten-answers",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 0,
    priority: 3,
    requiresEvent: HAMSTER_EVENTS.MEMORY_CORRECT,
    minRequiredEventCount: 10,
    minTimeSinceRequiredEventMs: 20 * 60 * 60 * 1000,
    text: "Ten answers, safely carried. I knew you would remember the road.",
  },
];

const pageThoughts = [
  ["compare", "I weighed two seeds. The smaller one had a better story."],
  ["days", "I counted the days until spring. Then I planted something, to help."],
  ["timer", "The kettle never watches the clock. A remarkable confidence."],
  ["memory", "I tied a knot to remember something. Now I remember the knot."],
  ["weather", "The sky has several opinions. I have brought a hat."],
  ["gentrail", "A path is a promise someone has walked on before."],
  ["images", "Keep that picture. Some afternoons do not happen twice."],
  ["stitch", "Two edges meeting. That is how a blanket becomes a blanket."],
  ["equation", "If we divide the last biscuit, there will still be two of us."],
  ["unique", "Every seed looks ordinary until you lose that particular seed."],
  ["neck", "Even a lookout must sometimes stop looking."],
  ["heartbeat", "There is a little drum in everyone. Mine is mostly announcing lunch."],
  ["babynames", "A name should fit in a whisper from the doorway."],
  ["burrow", "I swept before you came. The crumbs are new."],
].map(([page, text]) => ({
  id: `ambient-page-${page}`,
  event: HAMSTER_EVENTS.MANUAL_REVEAL,
  page: `/${page}.html`,
  stage: 1,
  minRelationshipCount: 4,
  minAgeMs: 2 * 24 * 60 * 60 * 1000,
  priority: 1,
  text,
}));

const familiarThoughts = [
  ["spare-cup", "I used to put the spare cup away. It lives on the table now."],
  ["small-road", "You need not have travelled far to have something to tell me."],
  ["unfinished-map", "I left a corner of the map blank. We may want somewhere new."],
  ["ordinary-day", "Nothing happened today. I thought you might like to sit through some of it."],
  ["provisions", "I packed enough for two. An old habit, recently acquired."],
  ["homeward", "The road looks different when you know which window is yours."],
].map(([id, text]) => ({
  id: `ambient-familiar-${id}`,
  event: HAMSTER_EVENTS.MANUAL_REVEAL,
  stage: 2,
  minRelationshipCount: 10,
  minAgeMs: 7 * 24 * 60 * 60 * 1000,
  text,
}));

const clockThoughts = [
  ["morning", "The morning has not made up its mind yet. Breakfast might persuade it."],
  ["day", "The sunlight has reached the good floorboard. I have moved my work there."],
  ["evening", "I lit the lamp before it was needed. It is good to have something ready."],
  ["night", "You are awake too. I shall make the kettle quieter."],
].map(([timeBand, text]) => ({
  id: `ambient-clock-${timeBand}`,
  event: HAMSTER_EVENTS.MANUAL_REVEAL,
  stage: 1,
  minRelationshipCount: 4,
  minAgeMs: 3 * 24 * 60 * 60 * 1000,
  detailEquals: { timeBand },
  text,
}));

export const hamsterEncounters = Object.freeze([
  {
    id: "quest-wake-offer",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 0,
    priority: 10,
    startsQuest: "wake-in-three",
    text: "The bell was meant to wake me. Three minutes ought to do.",
  },
  {
    id: "quest-wake-complete-long",
    event: HAMSTER_EVENTS.TIMER_COMPLETED,
    stage: 0,
    priority: 12,
    requiresActiveQuest: "wake-in-three",
    minDurationMs: 10 * 60 * 1000,
    completesQuest: "wake-in-three",
    awardsKeepsake: "brass-button",
    presentation: "cameo",
    text: "You let the bell wander. I dreamed an entire additional chapter.",
  },
  {
    id: "quest-wake-complete-night",
    event: HAMSTER_EVENTS.TIMER_COMPLETED,
    stage: 0,
    priority: 11,
    requiresActiveQuest: "wake-in-three",
    minDurationMs: 3 * 60 * 1000,
    detailEquals: { timeBand: "night" },
    completesQuest: "wake-in-three",
    awardsKeepsake: "brass-button",
    presentation: "cameo",
    text: "Three minutes in the dark. Even the road held its breath.",
  },
  {
    id: "quest-wake-complete",
    event: HAMSTER_EVENTS.TIMER_COMPLETED,
    stage: 0,
    priority: 10,
    requiresActiveQuest: "wake-in-three",
    minDurationMs: 3 * 60 * 1000,
    completesQuest: "wake-in-three",
    awardsKeepsake: "brass-button",
    presentation: "cameo",
    text: "The bell remembered. Somewhere, a very small latch has lifted.",
  },
  {
    id: "quest-weather-offer",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 0,
    priority: 10,
    startsQuest: "fetch-the-weather",
    requiresCompletedQuest: "wake-in-three",
    minTimeSinceCompletedQuestMs: 20 * 60 * 60 * 1000,
    text: "The door has been listening to the sky. Tell me what it heard.",
  },
  {
    id: "quest-weather-wet-night",
    event: HAMSTER_EVENTS.WEATHER_CHECKED,
    stage: 0,
    priority: 12,
    requiresActiveQuest: "fetch-the-weather",
    detailEquals: { wet: true, timeBand: "night" },
    completesQuest: "fetch-the-weather",
    awardsKeepsake: "rain-darkened-cloak",
    presentation: "cameo",
    text: "Rain in the night. Leave the lantern low; the cloak knows the way.",
  },
  {
    id: "quest-weather-wet",
    event: HAMSTER_EVENTS.WEATHER_CHECKED,
    stage: 0,
    priority: 11,
    requiresActiveQuest: "fetch-the-weather",
    detailEquals: { wet: true },
    completesQuest: "fetch-the-weather",
    awardsKeepsake: "rain-darkened-cloak",
    presentation: "cameo",
    text: "Rain, then. The old cloak has been waiting for an excuse.",
  },
  {
    id: "quest-weather-dry",
    event: HAMSTER_EVENTS.WEATHER_CHECKED,
    stage: 0,
    priority: 10,
    requiresActiveQuest: "fetch-the-weather",
    detailEquals: { wet: false },
    completesQuest: "fetch-the-weather",
    awardsKeepsake: "sun-warmed-cloak",
    presentation: "cameo",
    text: "No rain. We shall take the cloak anyway and call it foresight.",
  },
  {
    id: "gentrail-rain-cloak",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    page: "/gentrail.html",
    stage: 0,
    priority: 5,
    requiresKeepsake: "rain-darkened-cloak",
    text: "The cloak has dried. The road may attempt its worst.",
  },
  {
    id: "gentrail-sun-cloak",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    page: "/gentrail.html",
    stage: 0,
    priority: 5,
    requiresKeepsake: "sun-warmed-cloak",
    text: "We carried a cloak through clear weather. Best not waste the practice.",
  },
  {
    id: "memory-three-correct",
    event: HAMSTER_EVENTS.MEMORY_CORRECT,
    stage: 0,
    minEventCount: 3,
    presentation: "cameo",
    text: "Three riddles answered. I would have let you through the mountain after one.",
  },
  {
    id: "memory-ten-correct",
    event: HAMSTER_EVENTS.MEMORY_CORRECT,
    stage: 0,
    minEventCount: 10,
    presentation: "cameo",
    text: "Ten answers safely carried. I forgot why I went into the pantry.",
  },
  {
    id: "remembered-black-seed",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 1,
    priority: 2,
    requiresKeepsake: "black-seed",
    text: "I put the black seed by the door. Some things wait for a season we cannot name yet.",
  },
  {
    id: "remembered-cloak-journey",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 1,
    priority: 2,
    requiresCompletedQuest: "fetch-the-weather",
    minTimeSinceCompletedQuestMs: 3 * 24 * 60 * 60 * 1000,
    text: "We asked the sky for permission once. The cloak and I have decided we can simply go.",
  },
  ...pageThoughts,
  ...familiarThoughts,
  ...clockThoughts,
  ...rememberedMoments,
  ...wanderingThoughts,
  {
    id: "ambient-machinery",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 1,
    minRelationshipCount: 4,
    text: "I was only checking the machinery. The wheel goes ever on.",
  },
  {
    id: "ambient-silence",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 1,
    minRelationshipCount: 4,
    text: "You may stay. I was not using the silence.",
  },
  {
    id: "ambient-returned",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 2,
    minRelationshipCount: 10,
    text: "You came back.",
  },
  {
    id: "ambient-wheel-arrangement",
    event: HAMSTER_EVENTS.MANUAL_REVEAL,
    stage: 2,
    minRelationshipCount: 10,
    text: "The wheel and I have reached an arrangement. Neither of us will discuss it.",
  },
  {
    id: "timer-first-ending",
    event: HAMSTER_EVENTS.TIMER_COMPLETED,
    stage: 1,
    minRelationshipCount: 4,
    presentation: "cameo",
    text: "The timer is empty. You are still here.",
  },
  {
    id: "timer-final-second",
    event: HAMSTER_EVENTS.TIMER_COMPLETED,
    stage: 2,
    minRelationshipCount: 10,
    minEventCount: 2,
    presentation: "cameo",
    text: "I put the final second beneath the bedding.",
  },
  {
    id: "timer-after-zero",
    event: HAMSTER_EVENTS.TIMER_COMPLETED,
    stage: 2,
    minRelationshipCount: 10,
    minEventCount: 2,
    presentation: "cameo",
    text: "Zero is not an amount of time. It is what the timer does afterward.",
  },
  {
    id: "timer-kettle",
    event: HAMSTER_EVENTS.TIMER_COMPLETED,
    stage: 1,
    minRelationshipCount: 4,
    minEventCount: 2,
    presentation: "cameo",
    text: "There. A little clearing in the day. We could put a kettle in it.",
  },
  {
    id: "timer-long-watch",
    event: HAMSTER_EVENTS.TIMER_COMPLETED,
    stage: 2,
    minRelationshipCount: 10,
    minDurationMs: 25 * 60 * 1000,
    minEventCount: 3,
    presentation: "cameo",
    text: "I kept watch while you worked. Nothing got past except the afternoon.",
  },
  {
    id: "timer-night-lamp",
    event: HAMSTER_EVENTS.TIMER_COMPLETED,
    stage: 2,
    minRelationshipCount: 10,
    minEventCount: 3,
    detailEquals: { timeBand: "night" },
    presentation: "cameo",
    text: "The bell has finished. I will leave the lamp on while you find your slippers.",
  },
  {
    id: "memory-twenty-correct",
    event: HAMSTER_EVENTS.MEMORY_CORRECT,
    stage: 1,
    minRelationshipCount: 4,
    minEventCount: 20,
    presentation: "cameo",
    text: "Twenty things remembered. I have written down where I put the pencil.",
  },
  {
    id: "memory-fifty-correct",
    event: HAMSTER_EVENTS.MEMORY_CORRECT,
    stage: 2,
    minRelationshipCount: 10,
    minEventCount: 50,
    presentation: "cameo",
    text: "Fifty answers. If the mountain asks us a riddle, I shall let you speak.",
  },
  {
    id: "weather-returning-rain",
    event: HAMSTER_EVENTS.WEATHER_CHECKED,
    stage: 1,
    minRelationshipCount: 4,
    requiresCompletedQuest: "fetch-the-weather",
    minTimeSinceCompletedQuestMs: 20 * 60 * 60 * 1000,
    detailEquals: { wet: true },
    presentation: "cameo",
    text: "Rain again. The roof is telling its favourite story.",
  },
  {
    id: "weather-clear-road",
    event: HAMSTER_EVENTS.WEATHER_CHECKED,
    stage: 1,
    minRelationshipCount: 4,
    requiresCompletedQuest: "fetch-the-weather",
    minTimeSinceCompletedQuestMs: 20 * 60 * 60 * 1000,
    detailEquals: { wet: false },
    presentation: "cameo",
    text: "A clear sky. I have opened the door a little wider than necessary.",
  },
  {
    id: "weather-night-home",
    event: HAMSTER_EVENTS.WEATHER_CHECKED,
    stage: 2,
    minRelationshipCount: 10,
    requiresCompletedQuest: "fetch-the-weather",
    minTimeSinceCompletedQuestMs: 2 * 24 * 60 * 60 * 1000,
    detailEquals: { timeBand: "night" },
    presentation: "cameo",
    text: "Whatever the sky is doing, there is a dry chair here.",
  },
]);
